<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-14T00:35:51 EST" name="Default suite" finished-at="2024-11-14T00:35:53 EST" duration-ms="1956">
    <groups>
    </groups>
    <test started-at="2024-11-14T00:35:51 EST" name="Default test" finished-at="2024-11-14T00:35:53 EST" duration-ms="1956">
      <class name="pageTestEvents.GraphPageEvents">
        <test-method is-config="true" signature="setUP()[pri:0, instance:pageTestEvents.GraphPageEvents@495ee280]" started-at="2024-11-14T00:35:49 EST" name="setUP" finished-at="2024-11-14T00:35:51 EST" duration-ms="1769" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method is-config="true" signature="Login()[pri:0, instance:pageTestEvents.GraphPageEvents@495ee280]" started-at="2024-11-14T00:35:51 EST" name="Login" finished-at="2024-11-14T00:35:52 EST" duration-ms="829" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="graphPage()[pri:0, instance:pageTestEvents.GraphPageEvents@495ee280]" started-at="2024-11-14T00:35:52 EST" name="graphPage" finished-at="2024-11-14T00:35:52 EST" duration-ms="232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- graphPage -->
        <test-method signature="practiceQueT1()[pri:0, instance:pageTestEvents.GraphPageEvents@495ee280]" started-at="2024-11-14T00:35:52 EST" name="practiceQueT1" finished-at="2024-11-14T00:35:52 EST" duration-ms="344" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at pageTestEvents.GraphPageEvents.practiceQueT1(GraphPageEvents.java:165)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- practiceQueT1 -->
        <test-method is-config="true" signature="backtograph()[pri:0, instance:pageTestEvents.GraphPageEvents@495ee280]" started-at="2024-11-14T00:35:52 EST" name="backtograph" finished-at="2024-11-14T00:35:53 EST" duration-ms="212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- backtograph -->
        <test-method is-config="true" signature="Logout()[pri:0, instance:pageTestEvents.GraphPageEvents@495ee280]" started-at="2024-11-14T00:35:53 EST" name="Logout" finished-at="2024-11-14T00:35:53 EST" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:pageTestEvents.GraphPageEvents@495ee280]" started-at="2024-11-14T00:35:53 EST" name="tearDown" finished-at="2024-11-14T00:35:53 EST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pageTestEvents.GraphPageEvents -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
